// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVLBLOBRh8qx79PK60TvM2nOhqCW6dXc',
    appId: '1:956056495839:web:e778ae6adb2baf02e5ab6a',
    messagingSenderId: '956056495839',
    projectId: 'ecommerce-1d338',
    authDomain: 'ecommerce-1d338.firebaseapp.com',
    storageBucket: 'ecommerce-1d338.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZK7j5l3xJzBBy8KwjPKcafLJzAsuoJrQ',
    appId: '1:956056495839:android:560c74e362d31635e5ab6a',
    messagingSenderId: '956056495839',
    projectId: 'ecommerce-1d338',
    storageBucket: 'ecommerce-1d338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IRv7qtKOiCbso2_Y9vjj_1HVtjoYaUo',
    appId: '1:956056495839:ios:da260ec9e05164d9e5ab6a',
    messagingSenderId: '956056495839',
    projectId: 'ecommerce-1d338',
    storageBucket: 'ecommerce-1d338.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5IRv7qtKOiCbso2_Y9vjj_1HVtjoYaUo',
    appId: '1:956056495839:ios:da260ec9e05164d9e5ab6a',
    messagingSenderId: '956056495839',
    projectId: 'ecommerce-1d338',
    storageBucket: 'ecommerce-1d338.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOVLBLOBRh8qx79PK60TvM2nOhqCW6dXc',
    appId: '1:956056495839:web:1e9a26c92941a3f5e5ab6a',
    messagingSenderId: '956056495839',
    projectId: 'ecommerce-1d338',
    authDomain: 'ecommerce-1d338.firebaseapp.com',
    storageBucket: 'ecommerce-1d338.appspot.com',
  );
}
